[server]
port = "8080"
host = "0.0.0.0"
static_dir = "./static"
enable_cors = true
read_timeout_seconds = 30

[database]
path = "./staccato.db"
max_connections = 10

[music]
library_path = "./music"
supported_formats = [".flac", ".mp3", ".wav", ".m4a"]
watch_for_changes = true
scan_on_startup = true

[logging]
level = "info"
format = "text"
file = ""

[downloader]
enabled = true
yt_dlp_path = "yt-dlp"
max_concurrent_downloads = 2
audio_format = "mp3"
audio_quality = "0"
allowed_domains = ["youtube.com", "youtu.be", "soundcloud.com"]

[ngrok]
enabled = false
auth_token = ""
domain = ""
region = "us"
enable_auth = false
auth_provider = "google"

# Discord Rich Presence Configuration
[discord]
enabled = false
# You need to create a Discord application at https://discord.com/developers/applications
# and replace this with your actual Application ID
application_id = "1234567890123456789"
# These are image keys you can upload to your Discord application
large_image_key = "staccato_logo"
small_image_key = "music_note"

# Session Management Configuration
[session]
# Priority mode determines how multiple client sessions are handled:
# "play" - Play Priority: Client that clicks play gets priority, pausing others (like Spotify)
# "session" - Session Priority: Most recent session controls Discord RPC (current behavior)
# "session_play" - Session + Play Priority: Mix of both, background sessions continue playing
priority_mode = "session"

# How long before a session is considered inactive (in seconds)
activity_timeout = 30

# Discord RPC mode:
# "active_only" - Only show the active session in Discord
# "all_sessions" - Show all sessions (future feature)
# "background_aware" - Show active session but track background sessions (future feature)
discord_rpc_mode = "active_only"
